version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
  kafka-drop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
  muvi-api:
    image: muvi-api
    container_name: muvi-api
    restart: always
    links:
      - kafka:kafka
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - zookeeper